intro: "introduction"
next_with_decline: "Please read the following terms and conditions carefully and click either the 'Accept' or 'Decline' button at the bottom to continue."
introduction: "Introduction"
section_1: "section1"
section_1a: "section_1a"
section_1b: "section_1b."
rights_granted: "Rights Granted"
section_2: "section_2:"
section_3: "section_3"
active_defn_2: "active_defn_2"
section_4: "section_4"
section_5: "section_5:"
limitation_of_liability: "Limitation of Liability"
section_6: "To the extent permitted by applicable law..."
section_7: "Subject to any liability ...."
miscellaneous: "Miscellaneous"
section_8: "This Agreement shall be governed by ..."

